### ISSUE TITLE
newsArticle is not iterable

### ISSUE THREAD

**Issue by ChoongLiang** [fhamborg/news-please#107]
**Describe the bug**
TypeError: argument of type 'NewsArticle' is not iterable

**To Reproduce**
I did change some configurations in newsplease/examples/commoncrawl.py
(just dates though,  --> datetime.datetime(2019, 3, 1) as well as the end date)

Then I ran, 
`python3 -m newsplease.examples.commoncrawl`

and after downloading warc file from commoncrawl, the error came up during extraction.

**Expected behavior**
I was expecting the code to extract the articles from downloaded warc files.

**Screenshots**
https://drive.google.com/file/d/1EqR_GovNd_yDjwCvl2G1Gw1-aGT_QM6l/view?usp=sharing

**Versions (please complete the following information):**
 - OS: [MacOS 10.14]
 - Python Version [3.7]
 - news-please Version [1.3.13] (I am not sure, I git cloned yesterday..)

**Comment by fhamborg** [comment]
Works for me. Can you post the full log (as text)?

**Comment by joshclancy** [comment]
I am having a similar problem with the example newsplease.examples.downloadfromurl.py. I threw this into google colab for some messing around:

import json

url = 'https://www.rt.com/news/203203-ukraine-russia-troops-border/'
basepath = '/content/gdrive/'

article = NewsPlease.from_url(url)

with open(basepath + article['filename'] + '.json', 'w') as outfile:
    json.dump(article, outfile, indent=4, sort_keys=True)


But I got this error:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-12-43d60508b117> in <module>()
     11 article = NewsPlease.from_url(url)
     12 
---> 13 with open(basepath + article['filename'] + '.json', 'w') as outfile:
     14     json.dump(article, outfile, indent=4, sort_keys=True)

TypeError: 'NewsArticle' object is not subscriptable

**Comment by donglixp** [comment]
Hi @fhamborg ,

I googled the same error and reached here:

```bash
Traceback (most recent call last):
  File "/data/anaconda/envs/giga/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/data/anaconda/envs/giga/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/mnt/data/news-please/newsplease/examples/commoncrawl.py", line 169, in <module>
    main()
  File "/mnt/data/news-please/newsplease/examples/commoncrawl.py", line 165, in main
    continue_process=True)
  File "/mnt/data/news-please/newsplease/crawler/commoncrawl_crawler.py", line 297, in crawl_from_commoncrawl
    log_pathname_fully_extracted_warcs=__log_pathname_fully_extracted_warcs)
  File "/mnt/data/news-please/newsplease/crawler/commoncrawl_crawler.py", line 208, in __start_commoncrawl_extractor
    log_pathname_fully_extracted_warcs=__log_pathname_fully_extracted_warcs)
  File "/mnt/data/news-please/newsplease/crawler/commoncrawl_extractor.py", line 338, in extract_from_commoncrawl
    self.__run()
  File "/mnt/data/news-please/newsplease/crawler/commoncrawl_extractor.py", line 292, in __run
    self.__process_warc_gz_file(local_path_name)
  File "/mnt/data/news-please/newsplease/crawler/commoncrawl_extractor.py", line 237, in __process_warc_gz_file
    filter_pass, article = self.__filter_record(record)
  File "/mnt/data/news-please/newsplease/crawler/commoncrawl_extractor.py", line 121, in __filter_record
    publishing_date = self.__get_publishing_date(warc_record, article)
  File "/mnt/data/news-please/newsplease/crawler/commoncrawl_extractor.py", line 140, in __get_publishing_date
    if 'publish_date' in article:
TypeError: argument of type 'NewsArticle' is not iterable
```

**Comment by donglixp** [comment]
I proposed a PR in https://github.com/fhamborg/news-please/pull/118
