### ISSUE TITLE
Using multiple extraction processes : TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by rongybika** [fhamborg/news-please#116]
HI,
I've got this error using extraction processes (3), probably after finishing to parse one of the wrac files and adding to ,,fullyextractedwarcs.list".

**Log**
I have just one part of the log:

Traceback (most recent call last):
  File "C:\Users\Laptop\AppData\Local\Programs\Python\Python36\lib\multiprocessing\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\Laptop\AppData\Local\Programs\Python\Python36\lib\multiprocessing\pool.py", line 44, in mapstar
    return list(map(*args))
  File "e:\newsplease\news-please\newsplease\crawler\commoncrawl_crawler.py", line 208, in __start_commoncrawl_extractor
    log_pathname_fully_extracted_warcs=__log_pathname_fully_extracted_warcs)
  File "e:\newsplease\news-please\newsplease\crawler\commoncrawl_extractor.py", line 338, in extract_from_commoncrawl
    self.__run()
  File "e:\newsplease\news-please\newsplease\crawler\commoncrawl_extractor.py", line 292, in __run
    self.__process_warc_gz_file(local_path_name)
  File "e:\newsplease\news-please\newsplease\crawler\commoncrawl_extractor.py", line 278, in __process_warc_gz_file
    self.__register_fully_extracted_warc_file(self.__warc_download_url)
  File "e:\newsplease\news-please\newsplease\crawler\commoncrawl_extractor.py", line 93, in __register_fully_extracted_warc_file
    with open(self.__log_pathname_fully_extracted_warcs, 'a') as log_file:
TypeError: expected str, bytes or os.PathLike object, not NoneType

With latest version on Windows OS

Thank you

**Comment by fhamborg** [comment]
Hi, please use the bug report template. In this issue, steps to reproduce the issue are missing. Thanks,
