### ISSUE TITLE
RssCrawler doesn't support valid Rss XML

### ISSUE THREAD

**Issue by JeromeGill** [fhamborg/news-please#129]
**Describe the bug**
RssCrawler throws an exception due to not supporting valid RSS
https://github.com/fhamborg/news-please/blob/master/newsplease/single_crawler.py#L202

**To Reproduce**

dockerfile
```
FROM python:latest
RUN pip3 install news-please
```

The following sitelist.hjson
```
  "base_urls" : [
    {
           "url": "http://feeds.bbci.co.uk/news/world/latin_america/rss.xml",
           "crawler": "RssCrawler"
    }
```

**Expected behavior**

RssCrawler loaded and scrape the feed

**Log**

```
[newsplease.config:164|INFO] Loading config-file (/root/news-please-repo/config/config.cfg)
[newsplease.config:164|INFO] Loading config-file (/root/news-please-repo/config/config.cfg)
[__main__:200|ERROR] No crawlers (incl. fallbacks) found for url http://feeds.bbci.co.uk/news/world/latin_america/rss.xml.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/newsplease/single_crawler.py", line 265, in <module>
    SingleCrawler(cfg_file_path=sys.argv[1],
  File "/usr/local/lib/python3.8/site-packages/newsplease/single_crawler.py", line 117, in __init__
    crawler_class = self.get_crawler(self.crawler_name, site["url"])
  File "/usr/local/lib/python3.8/site-packages/newsplease/single_crawler.py", line 202, in get_crawler
    raise RuntimeError("No crawler found. Quit.")
RuntimeError: No crawler found. Quit.
[newsplease.__main__:269|INFO] Graceful stop called manually. Shutting down.
```

**Versions (please complete the following information):**
 - Python 3.8.0
 - news-please Version 1.4.3

**Comment by fhamborg** [comment]
Could this be related to this PR? https://github.com/fhamborg/news-please/pull/119

**Comment by JeromeGill** [comment]
That url in this issue is an atom feed, yeah

**Comment by quasar16** [comment]
Hi, 
I have the same issue when trying to use a google news rss feed (for example: https://news.google.com/rss/search?q=quantum&hl=en-US&gl=US&ceid=US:en). Did you fix the issue or is there any workaround?
