### ISSUE TITLE
Detect Language

### ISSUE THREAD

**Issue by jacarrasco** [fhamborg/news-please#131]
Hi,

It seems that the language detector needs a modification to check language. 

Traceback (most recent call last):
  File "/home/user/PycharmProjects/untitled2/testsel.py", line 329, in <module>
    article_np = NewsPlease.from_html(r.content)
  File "/home/user/.virtualenvs/untitled2/lib/python3.7/site-packages/newsplease/__init__.py", line 79, in from_html
    item = extractor.extract(item)
  File "/home/user/.virtualenvs/untitled2/lib/python3.7/site-packages/newsplease/pipeline/extractor/article_extractor.py", line 53, in extract
    article_candidates.append(extractor.extract(item))
  File "/home/user/.virtualenvs/untitled2/lib/python3.7/site-packages/newsplease/pipeline/extractor/extractors/abstract_extractor.py", line 64, in extract
    article_candidate.language = self._language(item)
  File "/home/user/.virtualenvs/untitled2/lib/python3.7/site-packages/newsplease/pipeline/extractor/extractors/lang_detect_extractor.py", line 52, in _language
    lang = detect(max(article_list))
  File "/home/user/.virtualenvs/untitled2/lib/python3.7/site-packages/langdetect/detector_factory.py", line 130, in detect
    return detector.detect()
  File "/home/user/.virtualenvs/untitled2/lib/python3.7/site-packages/langdetect/detector.py", line 136, in detect
    probabilities = self.get_probabilities()
  File "/home/user/.virtualenvs/untitled2/lib/python3.7/site-packages/langdetect/detector.py", line 143, in get_probabilities
    self._detect_block()
  File "/home/user/.virtualenvs/untitled2/lib/python3.7/site-packages/langdetect/detector.py", line 150, in _detect_block
    raise LangDetectException(ErrorCode.CantDetectError, 'No features in text.')
langdetect.lang_detect_exception.LangDetectException: No features in text.

It can be reproduced if i use this code:

import requests
from newsplease import NewsPlease

url_link = "https://www.elperiodico.com/es/trafico-barcelona-ahora/"
r = requests.get(url_link)
article_np = NewsPlease.from_html(r.content)

print(article_np)

I think it can be solved just modifying this line to line below. In the case reproduced, "article_list" length is 1 even with an empty text list.

 if len(article_list) > 1:

https://github.com/fhamborg/news-please/blob/db9d6e0a070d3e8cc0c79eecbc7423f8451da694/newsplease/pipeline/extractor/extractors/lang_detect_extractor.py#L51

**Comment by fhamborg** [comment]
Hi, please use the bug report issue template. Thanks

**Comment by fhamborg** [comment]
Also, it's recommended to use `NewsPlease.from_url()` if you want to crawl from a URL. Is there a specific reason why you use a request first?

**Comment by fhamborg** [comment]
should be fixed by https://github.com/fhamborg/news-please/issues/128
