### ISSUE TITLE
SitemapCrawler cannot crawl sites that are behind cloudflare

### ISSUE THREAD

**Issue by mxab** [fhamborg/news-please#134]
**Describe the bug**
Sites that are hosted via Cloudflare cannot be crawled via the SitemapCrawler
You get a 403 Forbidden error and the whole process terminates

**To Reproduce**
When you use a crawler

```
{
  "base_urls" : [
   {
     "url": "http://requestbin.net/r/17nizwd1" #request bin is hosted via cloudflare
   }
  ]
}

```
SitemapCrawler.supports_site fails since it does not set a user-agent header and uses the default python agent.

It works when you use the agent in the url_extractor.py requests
for example like
```
def follow_redirects(url):
   url = urllib2.Request(url, headers={'user-agent': CrawlerConfig.get_instance().get_scrapy_options() ['USER_AGENT']})
   opener = urllib2.build_opener(urllib2.HTTPRedirectHandler)    
   return opener.open(url).url
```

**Expected behavior**
Crawler should use agent header, process should not terminate but skip url

**Log**
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/newsplease/single_crawler.py", line 269, in <module>
    daemonize=sys.argv[5])
  File "/usr/local/lib/python3.7/site-packages/newsplease/single_crawler.py", line 117, in __init__
    crawler_class = self.get_crawler(self.crawler_name, site["url"])
  File "/usr/local/lib/python3.7/site-packages/newsplease/single_crawler.py", line 190, in get_crawler
    if supports_site(url):
  File "/usr/local/lib/python3.7/site-packages/newsplease/crawler/spiders/sitemap_crawler.py", line 69, in supports_site
    return UrlExtractor.sitemap_check(url)
  File "/usr/local/lib/python3.7/site-packages/newsplease/helper_classes/url_extractor.py", line 118, in sitemap_check
    response = urllib2.urlopen(UrlExtractor.get_sitemap_url(url, True))
  File "/usr/local/lib/python3.7/site-packages/newsplease/helper_classes/url_extractor.py", line 80, in get_sitemap_url
    "http://" + UrlExtractor.get_allowed_domain(url)
  File "/usr/local/lib/python3.7/site-packages/newsplease/helper_classes/url_extractor.py", line 65, in follow_redirects
    return opener.open(url).url
  File "/usr/local/Cellar/python/3.7.6/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python/3.7.6/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/Cellar/python/3.7.6/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python/3.7.6/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python/3.7.6/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
[newsplease.__main__:270|INFO] Graceful stop called manually. Shutting down.
```

**Versions (please complete the following information):**
 - OS: [e.g. MacOS 10.15.2]
 - Python Version [e.g. 3.7]
 - news-please Version [master]

*

**Comment by fhamborg** [comment]
newsplease by default does not imitate any of the common user agent strings, but check the documentation on how to change that.

**Comment by mxab** [comment]
Hi @fhamborg ,
I did rtfm ;)
My point was that the

`USER_AGENT = 'news-please (+http://www.example.com)'`

Is currently not considered in the `url_extractor.py` helper functions and therefore the crawler check crashes

If I apply the agent in theses methods I don't get the error
https://github.com/fhamborg/news-please/compare/master...mxab:master

**Comment by fhamborg** [comment]
Nice! Do your changes fully fix the issue you described? I currently don't have much time for NP, but if it's a working quick fix, I might be able to merge a PR.

**Comment by mxab** [comment]
As far as it looks like the changes in my PR #135 should fix this

**Comment by fhamborg** [comment]
cool, i just bumped news-please to the next version, incl. your PR. thanks for the great work! :)

**Comment by mxab** [comment]
Happy to help
