### ISSUE TITLE
Crawl Specific RSS Feeds on NYTimes

### ISSUE THREAD

**Issue by ericagredo** [fhamborg/news-please#162]
**Mandatory**
* [X ] I read the documentation ([readme](https://github.com/fhamborg/news-please/blob/master/README.md) and [wiki](https://github.com/fhamborg/news-please/wiki)).
* [ X] I searched other issues (including closed issues) and could not find any to be related. If you find related issues post them below or directly add your issue to the most related one.

Related issues:
* add them here

**Describe your question**
A clear and concise description of your question.
Hi, i'm trying to run a RssCrawler on NY Times, but on specific RSS feeds. For example, the NY Times Travel section has its own RSS Feed and i'd like to crawl that. However, it seems the "url" takes only the root domain, so it will always be www.nytimes.com. I tried putting https://www.nytimes.com/section/travel in the url section, but the only that is returned is the main NY Times RSS feed, so the home page. Not sure how to go about doing that. Thanks!

**Versions (please complete the following information):**
 - OS: [e.g. MacOS 10.2] macOS 10.15.4
 - Python Version [e.g. 3.6] python Python 3.7.3
 - news-please Version [e.g. 1.2] 1.5.3

**Intent (optional; we'll use this info to prioritize upcoming tasks to work on)**
* [ X] personal
* [ ] academic
* [ ] business
* [ ] other
* Some information on your project: 
Trying to visualize specific rss feeds

**Comment by fhamborg** [comment]
Hi Eric, could you please let me know how you use news-please? I assume you're using the CLI mode, as it is the only one supporting crawling from rss feeds. Also, could you paste a minimalistic version of your config file (which one did you modify?) to reproduce your issue?

**Comment by ericagredo** [comment]
Yeah I am using the CLI mode. I modified only sitelist.hjson. Here is what I have:
`{
  "base_urls" : [
    {
      "url": "https://www.nytimes.com/section/travel",
      "crawler": "RssCrawler",
      "daemonize": 3600
    }
  ]
}`

**Comment by fhamborg** [comment]
I guess this could easily be fixed, or rather this functionality could be added, by adding a new parameter that lets one define the URL to an RSS feed instead of the website's URL. I wanted to give this a try but I couldn't find the RSS feed specific for https://www.nytimes.com/section/travel Is there even one? If so, could you kindly post the URL to it?

**Comment by fabien-benoit-1984** [comment]
It's really stunning. RssClawler should have considered just RSS Feed. Yet instead, it does search for rss itself.

**Comment by princelySid** [comment]
> I guess this could easily be fixed, or rather this functionality could be added, by adding a new parameter that lets one define the URL to an RSS feed instead of the website's URL. I wanted to give this a try but I couldn't find the RSS feed specific for https://www.nytimes.com/section/travel Is there even one? If so, could you kindly post the URL to it?

This is the RSS feed: https://www.nytimes.com/svc/collections/v1/publish/https://www.nytimes.com/section/travel/rss.xml

**Comment by yksee** [comment]
When I tried using CLI and sitelist.hjson:
{ "base_urls" : [ { "url": "https://www.nytimes.com/svc/collections/v1/publish/https://www.nytimes.com/section/travel/rss.xml", "crawler": "RssCrawler", "daemonize": 3600 } ] }

I encountered the following:
__main__:218|ERROR] No crawlers (incl. fallbacks) found for url https://www.nytimes.com/svc/collections/v1/publish/https://www.nytimes.com/section/travel/rss.xml.
Traceback (most recent call last):
  File "/home/work/news-please-repo/venv/lib/python3.8/site-packages/newsplease/single_crawler.py", line 283, in <module>
    SingleCrawler(cfg_file_path=sys.argv[1],
  File "/home/work/news-please-repo/venv/lib/python3.8/site-packages/newsplease/single_crawler.py", line 119, in __init__
    crawler_class = self.get_crawler(self.crawler_name, site["url"])
  File "/home/work/news-please-repo/venv/lib/python3.8/site-packages/newsplease/single_crawler.py", line 220, in get_crawler
    raise RuntimeError("No crawler found. Quit.")
RuntimeError: No crawler found. Quit.

Am I doing this properly for RSS feeds?
