### ISSUE TITLE
handle ArticleExtractor error on empty html returns 

### ISSUE THREAD

**Issue by arcolife** [fhamborg/news-please#169]
**Mandatory**
* [x] I read the documentation ([readme](https://github.com/fhamborg/news-please/blob/master/README.md) and [wiki](https://github.com/fhamborg/news-please/wiki)).
* [x] I searched other issues (including closed issues) and could not find any to be related. If you find related issues post them below or directly add your issue to the most related one.

Related issues:
* https://github.com/fhamborg/news-please/issues/66

**Describe the bug**

An empty html reponse (for various reasons, like https://github.com/fhamborg/news-please/issues/66) is passed as it is `from_urls()` in [`__init__.py`](https://github.com/fhamborg/news-please/blob/master/newsplease/__init__.py#L117)
```py
html = SimpleCrawler.fetch_url(url, timeout=timeout)
results[url] = NewsPlease.from_html(html, url, download_date)
```

leading to `pipeline/extractor/extractors/newspaper_extractor.py:article.parse()` which triggers `newspaper.ArticleException`

This is even more problematic when using threaded mode, as then the scraping job is often stuck at `thread.join()`

- traceback:

```
In [17]: NewsPlease.from_url(url)
connection/timeout error: https://thegrayzone.com/2020/07/17/us-taiwan-lied-warning-world-health-organization-coronavirus/ ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
---------------------------------------------------------------------------
ArticleException                          Traceback (most recent call last)
<ipython-input-17-7489d1909aef> in <module>()
----> 1 NewsPlease.from_url(url)

/home/arcolife/.local/lib/python3.6/site-packages/newsplease/__init__.py in from_url(url, timeout)
     92         :rtype: NewsArticle, None
     93         """
---> 94         articles = NewsPlease.from_urls([url], timeout=timeout)
     95         if url in articles.keys():
     96             return articles[url]

/home/arcolife/.local/lib/python3.6/site-packages/newsplease/__init__.py in from_urls(urls, timeout)
    116             url = urls[0]
    117             html = SimpleCrawler.fetch_url(url, timeout=timeout)
--> 118             results[url] = NewsPlease.from_html(html, url, download_date)
    119         else:
    120             results = SimpleCrawler.fetch_urls(urls)

/home/arcolife/.local/lib/python3.6/site-packages/newsplease/__init__.py in from_html(html, url, download_date)
     77         item['download_date'] = download_date
     78         item['modified_date'] = None
---> 79         item = extractor.extract(item)
     80 
     81         tmp_article = ExtractedInformationStorage.extract_relevant_info(item)

/home/arcolife/.local/lib/python3.6/site-packages/newsplease/pipeline/extractor/article_extractor.py in extract(self, item)
     51 
     52         for extractor in self.extractor_list:
---> 53             article_candidate = extractor.extract(item)
     54             article_candidates.append(article_candidate)
     55 

/home/arcolife/.local/lib/python3.6/site-packages/newsplease/pipeline/extractor/extractors/newspaper_extractor.py in extract(self, item)
     28         article = Article('')
     29         article.set_html(item['spider_response'].body)
---> 30         article.parse()
     31         article_candidate.title = article.title
     32         article_candidate.description = article.meta_description

/home/arcolife/.local/lib/python3.6/site-packages/newspaper/article.py in parse(self)
    189 
    190     def parse(self):
--> 191         self.throw_if_not_downloaded_verbose()
    192 
    193         self.doc = self.config.get_parser().fromstring(self.html)

/home/arcolife/.local/lib/python3.6/site-packages/newspaper/article.py in throw_if_not_downloaded_verbose(self)
    527         """
    528         if self.download_state == ArticleDownloadState.NOT_STARTED:
--> 529             raise ArticleException('You must `download()` an article first!')
    530         elif self.download_state == ArticleDownloadState.FAILED_RESPONSE:
    531             raise ArticleException('Article `download()` failed with %s on URL %s' %

ArticleException: You must `download()` an article first!

```

**To Reproduce**

```py
from newspaper import  ArticleException

url = "https://thegrayzone.com/2020/07/17/us-taiwan-lied-warning-world-health-organization-coronavirus/"
try:
    NewsPlease.from_url(url)
except ArticleException:
    print("NO article downloaded")
```

**Expected behavior**
should just give me an empty article maintext / other relevant fields in the object returned.

**Log**

```
connection/timeout error: https://thegrayzone.com/2020/07/17/us-taiwan-lied-warning-world-health-organization-coronavirus/ ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
NO article downloaded
```

**Versions (please complete the following information):**
 - OS: Ubuntu 18.04.4 LTS
 - Python Version: 3.6.9
 - news-please Version: `commit c79e8c35950dbfd30e1d5f4f3d291d97de488bad (HEAD -> master, origin/master, origin/HEAD)`

**Comment by frankier** [comment]
I also get this when extracting WARCs from news-crawl.

```
2021-02-08 07:40:53 [newsplease.crawler.commoncrawl_extractor] ERROR: <traceback object at 0x7f874b007548>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/newsplease/crawler/commoncrawl_extractor.py", line 257, in __process_warc_gz_file
    filter_pass, article = self.filter_record(record)
  File "/opt/coviddash/ingress/covidmarch.py", line 31, in filter_record
    passed_filters, article = super().filter_record(warc_record, article)
  File "/usr/local/lib/python3.7/dist-packages/newsplease/crawler/commoncrawl_extractor.py", line 121, in filter_record
    article = self._from_warc(warc_record)
  File "/usr/local/lib/python3.7/dist-packages/newsplease/crawler/commoncrawl_extractor.py", line 233, in _from_warc
    return NewsPlease.from_warc(record, decode_errors="replace" if self.__ignore_unicode_errors else "strict")
  File "/usr/local/lib/python3.7/dist-packages/newsplease/__init__.py", line 49, in from_warc
    article = NewsPlease.from_html(html, url=url, download_date=download_date)
  File "/usr/local/lib/python3.7/dist-packages/newsplease/__init__.py", line 83, in from_html
    item = extractor.extract(item)
  File "/usr/local/lib/python3.7/dist-packages/newsplease/pipeline/extractor/article_extractor.py", line 53, in extract
    article_candidate = extractor.extract(item)
  File "/usr/local/lib/python3.7/dist-packages/newsplease/pipeline/extractor/extractors/newspaper_extractor.py", line 30, in extract
    article.parse()
  File "/usr/local/lib/python3.7/dist-packages/newspaper/article.py", line 191, in parse
    self.throw_if_not_downloaded_verbose()
  File "/usr/local/lib/python3.7/dist-packages/newspaper/article.py", line 529, in throw_if_not_downloaded_verbose
    raise ArticleException('You must `download()` an article first!')
newspaper.article.ArticleException: You must `download()` an article first!
```
