### ISSUE TITLE
RecursiveCrawler : ValueError('Missing scheme in request url: %s' % self._url)

### ISSUE THREAD

**Issue by basingh** [fhamborg/news-please#174]
**Mandatory**
* [ x] I read the documentation ([readme](https://github.com/fhamborg/news-please/blob/master/README.md) and [wiki](https://github.com/fhamborg/news-please/wiki)).
* [x ] I searched other issues (including closed issues) and could not find any to be related. If you find related issues post them below or directly add your issue to the most related one.

Related issues:
* add them here

**Describe your question**
Getting a weird error while running Recursive crawler on a website while the RssCrawler works just fine.

Config:

```
 "base_urls" : [
    {
      # Start crawling from faz.net
      "url": "https://www.smh.com.au/"
      # "url": "https://www.smh.com.au/rss"
      # Overwrite the default crawler and use th RecursiveCrawler instead
      "crawler": "RecursiveCrawler",

      # Because this site is weirt, use the
      # meta_contains_article_keyword-heuristic and disable all others because
      # overwrite will merge the defaults from "newscrawler.cfg" with
      # this
      "overwrite_heuristics": {
         "is_not_from_subdomain": true
        "meta_contains_article_keyword": true,
        "og_type": false,
        "linked_headlines": false,
        "self_linked_headlines": false
      },
      # Also state that in the condition, all heuristics used in the condition
      # have to be activated in "overwrite_heuristics" (or default) as well.
      "pass_heuristics_condition": "meta_contains_article_keyword"
    }
```

Error message: `ValueError('Missing scheme in request url: %s' % self._url)`
```
root@v1:~/news-please-repo/config# news-please
[newsplease.config:161|INFO] Loading config-file (/root/news-please-repo/config/config.cfg)
[newsplease.config:161|INFO] Loading config-file (/root/news-please-repo/config/config.cfg)
[__main__:260|INFO] Removed /root/news-please-repo/.resume_jobdir/ae464e0cafd025de534f26069b1856ea since '--resume' was not passed to initial.py or this crawler was daemonized.
[scrapy.utils.log:144|INFO] Scrapy 2.3.0 started (bot: news-please)
[scrapy.utils.log:150|INFO] Versions: lxml 4.5.2.0, libxml2 2.9.10, cssselect 1.1.0, parsel 1.6.0, w3lib 1.22.0, Twisted 17.9.0, Python 3.6.9 (default, Jul 17 2020, 12:50:27) - [GCC 8.4.0], pyOpenSSL 17.5.0 (OpenSSL 1.1.1  11 Sep 2018), cryptography 2.1.4, Platform Linux-4.15.0-88-generic-x86_64-with-Ubuntu-18.04-bionic
[scrapy.crawler:60|INFO] Overridden settings:
{'BOT_NAME': 'news-please',
 'CONCURRENT_REQUESTS_PER_DOMAIN': 4,
 'LOG_FORMAT': '[%(name)s:%(lineno)d|%(levelname)s] %(message)s',
 'LOG_LEVEL': 'INFO',
 'NEWSPIDER_MODULE': 'newsplease.crawler.spiders',
 'ROBOTSTXT_OBEY': True,
 'SPIDER_MODULES': ['newsplease.crawler.spiders'],
 'USER_AGENT': 'news-please (+https://www.example.com/)'}
[scrapy.extensions.telnet:55|INFO] Telnet Password: b08b9d218a7f22f1
[scrapy.middleware:48|INFO] Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.memusage.MemoryUsage',
 'scrapy.extensions.logstats.LogStats',
 'scrapy.extensions.spiderstate.SpiderState']
[scrapy.middleware:48|INFO] Enabled downloader middlewares:
['scrapy.downloadermiddlewares.robotstxt.RobotsTxtMiddleware',
 'scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
[scrapy.middleware:48|INFO] Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
[newsplease.pipeline.extractor.article_extractor:34|INFO] Extractor initialized: newspaper_extractor
[newsplease.pipeline.extractor.article_extractor:34|INFO] Extractor initialized: readability_extractor
[newsplease.pipeline.extractor.article_extractor:34|INFO] Extractor initialized: date_extractor
[newsplease.pipeline.extractor.article_extractor:34|INFO] Extractor initialized: lang_detect_extractor
[elasticsearch:241|INFO] HEAD http://localhost:9200/ [status:200 request:0.002s]
[scrapy.middleware:48|INFO] Enabled item pipelines:
['newsplease.pipeline.pipelines.ArticleMasterExtractor',
 'newsplease.pipeline.pipelines.ElasticsearchStorage']
[scrapy.core.engine:267|INFO] Spider opened
[scrapy.extensions.logstats:48|INFO] Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
[scrapy.extensions.telnet:69|INFO] Telnet console listening on 127.0.0.1:6023
[scrapy.core.scraper:168|ERROR] Spider error processing <GET https://www.smh.com.au/> (referer: None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/scrapy/utils/defer.py", line 120, in iter_errback
    yield next(it)
  File "/usr/local/lib/python3.6/dist-packages/scrapy/utils/python.py", line 347, in __next__
    return next(self.data)
  File "/usr/local/lib/python3.6/dist-packages/scrapy/utils/python.py", line 347, in __next__
    return next(self.data)
  File "/usr/local/lib/python3.6/dist-packages/scrapy/core/spidermw.py", line 64, in _evaluate_iterable
    for r in iterable:
  File "/usr/local/lib/python3.6/dist-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/usr/local/lib/python3.6/dist-packages/scrapy/core/spidermw.py", line 64, in _evaluate_iterable
    for r in iterable:
  File "/usr/local/lib/python3.6/dist-packages/scrapy/spidermiddlewares/referer.py", line 340, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/usr/local/lib/python3.6/dist-packages/scrapy/core/spidermw.py", line 64, in _evaluate_iterable
    for r in iterable:
  File "/usr/local/lib/python3.6/dist-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/usr/local/lib/python3.6/dist-packages/scrapy/core/spidermw.py", line 64, in _evaluate_iterable
    for r in iterable:
  File "/usr/local/lib/python3.6/dist-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/usr/local/lib/python3.6/dist-packages/scrapy/core/spidermw.py", line 64, in _evaluate_iterable
    for r in iterable:
  File "/usr/local/lib/python3.6/dist-packages/newsplease/crawler/spiders/recursive_crawler.py", line 50, in parse
    self.ignore_file_extensions):
  File "/usr/local/lib/python3.6/dist-packages/newsplease/helper_classes/parse_crawler.py", line 107, in recursive_requests
    for href in response.css("a::attr('href')").extract() if re.match(
  File "/usr/local/lib/python3.6/dist-packages/newsplease/helper_classes/parse_crawler.py", line 111, in <listcomp>
    and len(re.match(ignore_regex, response.urljoin(href)).group(0)) == 0
  File "/usr/local/lib/python3.6/dist-packages/scrapy/http/request/__init__.py", line 25, in __init__
    self._set_url(url)
  File "/usr/local/lib/python3.6/dist-packages/scrapy/http/request/__init__.py", line 69, in _set_url
    raise ValueError('Missing scheme in request url: %s' % self._url)
ValueError: Missing scheme in request url: javascript:void(0)
[scrapy.core.engine:304|INFO] Closing spider (finished)
[scrapy.statscollectors:47|INFO] Dumping Scrapy stats:
{'downloader/request_bytes': 1117,
 'downloader/request_count': 5,
 'downloader/request_method_count/GET': 5,
 'downloader/response_bytes': 147290,
 'downloader/response_count': 5,
 'downloader/response_status_count/200': 3,
 'downloader/response_status_count/301': 2,
 'elapsed_time_seconds': 0.45393,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2020, 8, 23, 2, 17, 19, 661513),
 'log_count/ERROR': 1,
 'log_count/INFO': 15,
 'memusage/max': 67747840,
 'memusage/startup': 67747840,
 'response_received_count': 3,
 'robotstxt/request_count': 2,
 'robotstxt/response_count': 2,
 'robotstxt/response_status_count/200': 2,
 'scheduler/dequeued': 2,
 'scheduler/dequeued/disk': 2,
 'scheduler/enqueued': 2,
 'scheduler/enqueued/disk': 2,
 'spider_exceptions/ValueError': 1,
 'start_time': datetime.datetime(2020, 8, 23, 2, 17, 19, 207583)}
[scrapy.core.engine:335|INFO] Spider closed (finished)
[newsplease.__main__:276|INFO] Graceful stop called manually. Shutting down.
```

Interestingly if I replace this with RssCrawler I get valid responses.
The problem with RssCrawler os it does not go to each RSS xml lister here: https://www.smh.com.au/rssheadlines
Causing missing data

**Versions (please complete the following information):**
 - OS: [e.g. MacOS 10.2] : ubuntu/bionic64
 - Python Version [e.g. 3.6] : Python 3.6.9
 - news-please Version [e.g. 1.2]

**Intent (optional; we'll use this info to prioritize upcoming tasks to work on)**
* [x] personal
* [ ] academic
* [ ] business
* [ ] other
* Some information on your project:

**Comment by basingh** [comment]
I somehow couldn't complete the run for this from source code. Getting following errors:

```
python __main__.py 
[newsplease.config:161|INFO] Loading config-file (/Users/.../news-please/news-please-repo//config/config.cfg)
[newsplease.config:161|INFO] Loading config-file (/Users/.../news-please/news-please-repo//config/config.cfg)
[newsplease.config:161|INFO] Loading config-file (/Users/.../news-please/news-please-repo//config/config.cfg)
[newsplease.config:161|INFO] Loading config-file (/Users/.../news-please/news-please-repo//config/config.cfg)
Traceback (most recent call last):
  File "/Users/.../news-please/newsplease/single_crawler.py", line 287, in <module>
    daemonize=sys.argv[5])
  File "/Users/.../news-please/newsplease/single_crawler.py", line 142, in __init__
    self.cfg.get_working_path())
TypeError: __init__() takes 8 positional arguments but 9 were given
Traceback (most recent call last):
  File "/Users/.../news-please/newsplease/single_crawler.py", line 287, in <module>
    daemonize=sys.argv[5])
  File "/Users/.../news-please/newsplease/single_crawler.py", line 142, in __init__
    self.cfg.get_working_path())
TypeError: __init__() takes 8 positional arguments but 9 were given
Traceback (most recent call last):
  File "/Users/.../news-please/newsplease/single_crawler.py", line 287, in <module>
    daemonize=sys.argv[5])
  File "/Users/.../news-please/newsplease/single_crawler.py", line 142, in __init__
    self.cfg.get_working_path())
TypeError: __init__() takes 8 positional arguments but 9 were given
[__main__:276|INFO] Graceful stop called manually. Shutting down.
```

Have you seen this before? I do see in single_crawler.py 8 params are passed : https://github.com/fhamborg/news-please/blob/master/newsplease/single_crawler.py#L135

However helper.py itself is looking for 9 , possibly why the error above: https://github.com/fhamborg/news-please/blob/5d30d8c82416db7d4bf805aa30501266879cf780/newsplease/helper.py#L21

Not sure what I am missing here

**Comment by basingh** [comment]
nvm, got this working. Fixed the file structure in git checkout using documentation here: https://github.com/fhamborg/news-please/wiki/developer-guide#files

following which the fix on `parse_crawler.py` worked just fine. 
Thanks for help.
