### ISSUE TITLE
CommonCrawl.py example

### ISSUE THREAD

**Issue by keimiii** [fhamborg/news-please#207]
**Mandatory**
* [x] I read the documentation ([readme](https://github.com/fhamborg/news-please/blob/master/README.md) and [wiki](https://github.com/fhamborg/news-please/wiki)).
* [x] I searched other issues (including closed issues) and could not find any to be related. If you find related issues post them below or directly add your issue to the most related one.

**Describe the bug**
A clear and concise description of what the bug is. This must include a full stack-trace (if applicable).

**To Reproduce**
python3 -m newsplease.example.commoncrawl

**Expected behavior**
Files from commoncrawl to be saved to local directory

**Log**
```
my_local_download_dir_warc=./cc_download_warc/
my_local_download_dir_article=./cc_download_articles/
my_delete_warc_after_extraction=True
my_number_of_extraction_processes=1
INFO:newsplease.crawler.commoncrawl_crawler:executing: aws s3 ls --recursive s3://commoncrawl/crawl-data/CC-NEWS/ --no-sign-request > C:\Users\leong\AppData\Local\Temp\tmppig4mis9 && awk "{ print $4 }" C:\Users\leong\AppData\Local\Temp\tmppig4mis9
Traceback (most recent call last):
  File "C:\Users\leong\anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\leong\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\leong\git_environment\news-please\newsplease\examples\commoncrawl.py", line 183, in <module>
    main()
  File "C:\Users\leong\git_environment\news-please\newsplease\examples\commoncrawl.py", line 164, in main
    commoncrawl_crawler.crawl_from_commoncrawl(on_valid_article_extracted,
  File "C:\Users\leong\git_environment\news-please\newsplease\crawler\commoncrawl_crawler.py", line 303, in crawl_from_commoncrawl
    cc_news_crawl_names = __get_remote_index(warc_files_start_date)
  File "C:\Users\leong\git_environment\news-please\newsplease\crawler\commoncrawl_crawler.py", line 154, in __get_remote_index
    raise Exception(stdout_data)
Exception: The process cannot access the file because it is being used by another process.
```

**Versions (please complete the following information):**
 - OS: 10.0.19041 N/A Build 19041
 - Python Version Python 3.8.5
 - news-please Version 1.5.18

**Intent (optional; we'll use this info to prioritize upcoming tasks to work on)**
* [ ] personal
* [ ] academic
* [x] business
* [ ] other
* Some information on your project:

**Comment by fhamborg** [comment]
I cannot reproduce this issue on my side, but when looking at the code of news-please, the only possible cause of this I can come up with is that you had two or more news-please instances running or there was still at least one other awscli process running (perhaps from an earlier run of news-please). I'd recomend to kill all such processes or just restart the system and give it another try.

**Comment by fhamborg** [comment]
Any news on this? If so, please feel free to reopen the issue :)

**Comment by ownchoice** [comment]
I just did a clean install of news-please and executed `python -m newsplease.examples.commoncrawl` and got this exact error.

**Comment by ownchoice** [comment]
> 
> 
> Any news on this? If so, please feel free to reopen the issue :)

How can I debug this further to provide more info?

```python
my_local_download_dir_warc=./cc_download_warc/
my_local_download_dir_article=./cc_download_articles/
my_delete_warc_after_extraction=True
my_number_of_extraction_processes=1
INFO:newsplease.crawler.commoncrawl_crawler:executing: aws s3 ls --recursive s3://commoncrawl/crawl-data/CC-NEWS/ --no-sign-request > C:\Users\winuser\AppData\Local\Temp\tmpfl11tmsd && awk "{ print $4 }" C:\Users\winuser\AppData\Local\Temp\tmpfl11tmsd
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python39\lib\site-packages\newsplease\examples\commoncrawl.py", line 190, in <module>
    main()
  File "C:\Program Files\Python39\lib\site-packages\newsplease\examples\commoncrawl.py", line 170, in main
    commoncrawl_crawler.crawl_from_commoncrawl(on_valid_article_extracted,
  File "C:\Program Files\Python39\lib\site-packages\newsplease\crawler\commoncrawl_crawler.py", line 330, in crawl_from_commoncrawl
    cc_news_crawl_names = __get_remote_index(warc_files_start_date, warc_files_end_date)
  File "C:\Program Files\Python39\lib\site-packages\newsplease\crawler\commoncrawl_crawler.py", line 174, in __get_remote_index
    raise Exception(stdout_data)
Exception: The process cannot access the file because it is being used by another process.
```
