### ISSUE TITLE
Unable to use cli "news-please

### ISSUE THREAD

**Issue by sachet14** [fhamborg/news-please#30]
Traceback (most recent call last):
  File "/usr/local/bin/news-please", line 7, in <module>
    from newsplease.__main__ import main
  File "/usr/local/lib/python2.7/site-packages/newsplease/__init__.py", line 13, in <module>
    from dotmap import DotMap
ImportError: No module named dotmap

**Comment by fhamborg** [comment]
This will be fixed in a future version. Until then, you can simply install the module yourself, e.g.,
pip3 install dotmap
or
pip install dotmap

**Comment by sachet14** [comment]
thanks solved it

**Comment by fhamborg** [comment]
fixed in 1d6c9699c82af10641abd213f6ac676829ae2868
