### ISSUE TITLE
AttributeError: 'module' object has no attribute 'request'

### ISSUE THREAD

**Issue by gambolputty** [fhamborg/news-please#34]
Hello!

After a fresh install I ran the example code from the readme file and it gave me the following error:

```
>>> from newsplease import NewsPlease
>>> article = NewsPlease.from_url('https://www.nytimes.com/2017/02/23/us/politics/cpac-stephen-bannon-reince-priebus.html?hp')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/gregor/anaconda/lib/python2.7/site-packages/newsplease/__init__.py", line 79, in from_url
    articles = NewsPlease.from_urls([url])
  File "/Users/gregor/anaconda/lib/python2.7/site-packages/newsplease/__init__.py", line 98, in from_urls
    html = SimpleCrawler.fetch_url(url)
  File "/Users/gregor/anaconda/lib/python2.7/site-packages/newsplease/crawler/simple_crawler.py", line 16, in fetch_url
    return SimpleCrawler._fetch_url(url, False)
  File "/Users/gregor/anaconda/lib/python2.7/site-packages/newsplease/crawler/simple_crawler.py", line 27, in _fetch_url
    req = urllib.request.Request(url, None, headers)
AttributeError: 'module' object has no attribute 'request'
```

Python 2.7.13 (on macOS 10.12.5 Sierra)
*urllib* is installed

Unfortunately I had no time for debugging. Might come back to it soon.

Gregor

**Comment by fhamborg** [comment]
Thanks for letting me know, I'll try to look into this next week.

**Comment by fhamborg** [comment]
Alright, should be fixed now. You can update your package via `pip install -U news-please`

**Comment by gambolputty** [comment]
Awesome. Vielen Dank :)

**Comment by jeradf** [comment]
The same issue exists for commoncrawl_extractor.py.

**Comment by fhamborg** [comment]
can you open a new ticket with a detailed bug report for the problem that specifically occurred to you? otherwise, i will not be able to fix the issue.
