### ISSUE TITLE
Version conflict on python-dateutil

### ISSUE THREAD

**Issue by Chialijuan** [fhamborg/news-please#49]
Hi there,
I'm currently running Python 2.7 on Ubuntu 14.04, installed news-please using pip.
Tried running news-please using cli and got this error:

Traceback (most recent call last):
  File "/usr/local/bin/news-please", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3147, in <module>
    @_call_aside
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3131, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3160, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 668, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 681, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 875, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (python-dateutil 2.6.1 (/usr/local/lib/python2.7/dist-packages), Requirement.parse('python-dateutil==2.4.0'), set(['newspaper']))

**Comment by fhamborg** [comment]
hmm that's strange, we require python-dateutil >= 2.4.0 so that should be fine
https://github.com/fhamborg/news-please/blob/21f9b8c44a9de8392e29df896b7a54bb080d18a9/setup.py#L45

**Comment by fhamborg** [comment]
oh, looks like you already have python-dateutil 2.6.1 installed on your computer, but the newspaper module requires this specifically to be 2.4.0. i'd recommend to use a virtual environment or remove the python-dateutil that's already installed on your computer before installing news-please
