### ISSUE TITLE
news-please not working throwing no directory error

### ISSUE THREAD

**Issue by SheebanWasi** [fhamborg/news-please#68]
sheebans-Air:downloads sheeban$ news-please 
[newsplease.config:165|INFO] Loading config-file (/Users/sheeban/news-please-repo/config/config.cfg)
Traceback (most recent call last):
  File "/Users/sheeban/anaconda3/bin/news-please", line 11, in <module>
    sys.exit(main())
  File "/Users/sheeban/anaconda3/lib/python3.6/site-packages/newsplease/__main__.py", line 647, in main
    plac.call(cli)
  File "/Users/sheeban/anaconda3/lib/python3.6/site-packages/plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "/Users/sheeban/anaconda3/lib/python3.6/site-packages/plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "/Users/sheeban/anaconda3/lib/python3.6/site-packages/newsplease/__main__.py", line 641, in cli
    NewsPleaseLauncher(cfg_file_path, resume, reset_elasticsearch, reset_json, reset_mysql, no_confirm)
  File "/Users/sheeban/anaconda3/lib/python3.6/site-packages/newsplease/__main__.py", line 123, in __init__
    self.json.setup(self.json_file_path)
  File "/Users/sheeban/anaconda3/lib/python3.6/site-packages/newsplease/config.py", line 268, in setup
    self.load_json(filepath)
  File "/Users/sheeban/anaconda3/lib/python3.6/site-packages/newsplease/config.py", line 276, in load_json
    self.__json_object = hjson.load(open(filepath, 'r'))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/sheeban/news-please-repo/config/sitelist.hjson'

**Comment by fhamborg** [comment]
please file a bug report using the bug report template. also see https://github.com/fhamborg/news-please#issues
