### ISSUE TITLE
ImportError: No module named 'hurry.filesize'

### ISSUE THREAD

**Issue by loveJasmine** [fhamborg/news-please#69]
Successfully installed hurry-1.0 py-1.4.34
mldl@ub1604:~/ub16_prj/news-please$ python3 -m newsplease.examples.commoncrawl
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/mldl/ub16_prj/news-please/newsplease/examples/commoncrawl.py", line 27, in <module>
    from ..crawler import commoncrawl_crawler as commoncrawl_crawler
  File "/home/mldl/ub16_prj/news-please/newsplease/crawler/commoncrawl_crawler.py", line 16, in <module>
    from ..crawler.commoncrawl_extractor import CommonCrawlExtractor
  File "/home/mldl/ub16_prj/news-please/newsplease/crawler/commoncrawl_extractor.py", line 15, in <module>
    from hurry.filesize import size
ImportError: No module named 'hurry.filesize'

**Comment by fhamborg** [comment]
please use the bug report template. thanks.
