### ISSUE TITLE
Error running test

### ISSUE THREAD

**Issue by wr6155** [fhamborg/news-please#76]
Hi,

When running news-please for test in terminal I receive the following error:
```
$ news-please
[newsplease.config:164|INFO] Loading config-file (/Users/user/news-please-repo/config/config.cfg)
[newsplease.config:164|INFO] Loading config-file (/Users/user/news-please-repo/config/config.cfg)
[newsplease.config:164|INFO] Loading config-file (/Users/user/news-please-repo/config/config.cfg)
[__main__:253|INFO] Removed /Users/user/news-please-repo/.resume_jobdir/f03a98d15778ac99eeb8c578aa8c224b since '--resume' was not passed to initial.py or this crawler was daemonized.
[newsplease.config:164|INFO] Loading config-file (/Users/user/news-please-repo/config/config.cfg)
[__main__:253|INFO] Removed /Users/user/news-please-repo/.resume_jobdir/5011d55eaa1b745eefb709134271e173 since '--resume' was not passed to initial.py or this crawler was daemonized.
Unhandled error in Deferred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/scrapy/crawler.py", line 171, in crawl
    return self._crawl(crawler, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/scrapy/crawler.py", line 175, in _crawl
    d = crawler.crawl(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1613, in unwindGenerator
    return _cancellableInlineCallbacks(gen)
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1529, in _cancellableInlineCallbacks
    _inlineCallbacks(None, g, status)
--- <exception caught here> ---
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/usr/local/lib/python3.7/site-packages/scrapy/crawler.py", line 80, in crawl
    self.engine = self._create_engine()
  File "/usr/local/lib/python3.7/site-packages/scrapy/crawler.py", line 105, in _create_engine
    return ExecutionEngine(self, lambda _: self.stop())
  File "/usr/local/lib/python3.7/site-packages/scrapy/core/engine.py", line 70, in __init__
    self.scraper = Scraper(crawler)
  File "/usr/local/lib/python3.7/site-packages/scrapy/core/scraper.py", line 71, in __init__
    self.itemproc = itemproc_cls.from_crawler(crawler)
  File "/usr/local/lib/python3.7/site-packages/scrapy/middleware.py", line 58, in from_crawler
    return cls.from_settings(crawler.settings, crawler)
  File "/usr/local/lib/python3.7/site-packages/scrapy/middleware.py", line 40, in from_settings
    mw = mwcls()
  File "/usr/local/lib/python3.7/site-packages/newsplease/pipeline/pipelines.py", line 52, in __init__
    self.extractor = article_extractor.Extractor(self.extractor_list)
  File "/usr/local/lib/python3.7/site-packages/newsplease/pipeline/extractor/article_extractor.py", line 25, in __init__
    module = importlib.import_module(__package__ + '.extractors.' + extractor)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
    
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
    
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
    
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
    
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
    
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
    
  File "/usr/local/lib/python3.7/site-packages/newsplease/pipeline/extractor/extractors/readability_extractor.py", line 3, in <module>
    from readability import Document
builtins.ImportError: cannot import name 'Document' from 'readability' (/usr/local/lib/python3.7/site-packages/readability/__init__.py)

[__main__:253|INFO] Removed /Users/user/news-please-repo/.resume_jobdir/861e0b7ca3034017282d27dce656d520 since '--resume' was not passed to initial.py or this crawler was daemonized.
Unhandled error in Deferred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/scrapy/crawler.py", line 171, in crawl
    return self._crawl(crawler, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/scrapy/crawler.py", line 175, in _crawl
    d = crawler.crawl(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1613, in unwindGenerator
    return _cancellableInlineCallbacks(gen)
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1529, in _cancellableInlineCallbacks
    _inlineCallbacks(None, g, status)
--- <exception caught here> ---
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/usr/local/lib/python3.7/site-packages/scrapy/crawler.py", line 80, in crawl
    self.engine = self._create_engine()
  File "/usr/local/lib/python3.7/site-packages/scrapy/crawler.py", line 105, in _create_engine
    return ExecutionEngine(self, lambda _: self.stop())
  File "/usr/local/lib/python3.7/site-packages/scrapy/core/engine.py", line 70, in __init__
    self.scraper = Scraper(crawler)
  File "/usr/local/lib/python3.7/site-packages/scrapy/core/scraper.py", line 71, in __init__
    self.itemproc = itemproc_cls.from_crawler(crawler)
  File "/usr/local/lib/python3.7/site-packages/scrapy/middleware.py", line 58, in from_crawler
    return cls.from_settings(crawler.settings, crawler)
  File "/usr/local/lib/python3.7/site-packages/scrapy/middleware.py", line 40, in from_settings
    mw = mwcls()
  File "/usr/local/lib/python3.7/site-packages/newsplease/pipeline/pipelines.py", line 52, in __init__
    self.extractor = article_extractor.Extractor(self.extractor_list)
  File "/usr/local/lib/python3.7/site-packages/newsplease/pipeline/extractor/article_extractor.py", line 25, in __init__
    module = importlib.import_module(__package__ + '.extractors.' + extractor)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
    
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
    
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
    
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
    
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
    
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
    
  File "/usr/local/lib/python3.7/site-packages/newsplease/pipeline/extractor/extractors/readability_extractor.py", line 3, in <module>
    from readability import Document
builtins.ImportError: cannot import name 'Document' from 'readability' (/usr/local/lib/python3.7/site-packages/readability/__init__.py)

Unhandled error in Deferred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/scrapy/crawler.py", line 171, in crawl
    return self._crawl(crawler, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/scrapy/crawler.py", line 175, in _crawl
    d = crawler.crawl(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1613, in unwindGenerator
    return _cancellableInlineCallbacks(gen)
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1529, in _cancellableInlineCallbacks
    _inlineCallbacks(None, g, status)
--- <exception caught here> ---
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/usr/local/lib/python3.7/site-packages/scrapy/crawler.py", line 80, in crawl
    self.engine = self._create_engine()
  File "/usr/local/lib/python3.7/site-packages/scrapy/crawler.py", line 105, in _create_engine
    return ExecutionEngine(self, lambda _: self.stop())
  File "/usr/local/lib/python3.7/site-packages/scrapy/core/engine.py", line 70, in __init__
    self.scraper = Scraper(crawler)
  File "/usr/local/lib/python3.7/site-packages/scrapy/core/scraper.py", line 71, in __init__
    self.itemproc = itemproc_cls.from_crawler(crawler)
  File "/usr/local/lib/python3.7/site-packages/scrapy/middleware.py", line 58, in from_crawler
    return cls.from_settings(crawler.settings, crawler)
  File "/usr/local/lib/python3.7/site-packages/scrapy/middleware.py", line 40, in from_settings
    mw = mwcls()
  File "/usr/local/lib/python3.7/site-packages/newsplease/pipeline/pipelines.py", line 52, in __init__
    self.extractor = article_extractor.Extractor(self.extractor_list)
  File "/usr/local/lib/python3.7/site-packages/newsplease/pipeline/extractor/article_extractor.py", line 25, in __init__
    module = importlib.import_module(__package__ + '.extractors.' + extractor)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
    
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
    
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
    
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
    
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
    
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
    
  File "/usr/local/lib/python3.7/site-packages/newsplease/pipeline/extractor/extractors/readability_extractor.py", line 3, in <module>
    from readability import Document
builtins.ImportError: cannot import name 'Document' from 'readability' (/usr/local/lib/python3.7/site-packages/readability/__init__.py)

[newsplease.__main__:270|INFO] Graceful stop called manually. Shutting down.
```

**Versions (please complete the following information):**
 - OS: [ MacOS 10.13.5]
 - Python Version [ 3.7.0]
 - news-please Version [1.2.50]

**Comment by wr6155** [comment]
Maybe this issue is related: https://stackoverflow.com/questions/25891955/importerror-no-module-named-readability

**Comment by fhamborg** [comment]
Please use the bug report issue template. This helps us tremendously to reproduce the issue, since the template makes sure that all relevant information is provided. You may edit your post by adding all information from the template and reopen this issue, or create a new issue based on the template.
