### ISSUE TITLE
[Error] urllib.error.URLError: <urlopen error unknown url type: ['https>

### ISSUE THREAD

**Issue by mabodx** [fhamborg/news-please#87]
**Describe the bug**
I just run the example code, and get the following error
```
Traceback (most recent call last):
  File "crawler.py", line 2, in <module>
    article = NewsPlease.from_url('https://www.nytimes.com/2017/02/23/us/politics/cpac-stephen-bannon-reince-priebus.html?hp')
  File "/Users/mabodx/anaconda/lib/python3.6/site-packages/newsplease/__init__.py", line 80, in from_url
    articles = NewsPlease.from_urls([url], timeout=timeout)
  File "/Users/mabodx/anaconda/lib/python3.6/site-packages/newsplease/__init__.py", line 103, in from_urls
    html = SimpleCrawler.fetch_url(url, timeout=timeout)
  File "/Users/mabodx/anaconda/lib/python3.6/site-packages/newsplease/crawler/simple_crawler.py", line 18, in fetch_url
    return SimpleCrawler._fetch_url(url, False, timeout=timeout)
  File "/Users/mabodx/anaconda/lib/python3.6/site-packages/newsplease/crawler/simple_crawler.py", line 31, in _fetch_url
    html = urllib.request.urlopen(req, data=None, timeout=timeout).read()
  File "/Users/mabodx/anaconda/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/mabodx/anaconda/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/Users/mabodx/anaconda/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/Users/mabodx/anaconda/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/Users/mabodx/anaconda/lib/python3.6/urllib/request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/Users/mabodx/anaconda/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error EOF occurred in violation of protocol (_ssl.c:749)>
```

**To Reproduce**
I just run the example code, and get the following error

```
from newsplease import NewsPlease
article = NewsPlease.from_url('https://www.nytimes.com/2017/02/23/us/politics/cpac-stephen-bannon-reince-priebus.html?hp')
print(article.title)
```

**Expected behavior**
I think I suppose to get the same result as https://github.com/fhamborg/news-please/blob/master/newsplease/examples/sample.json

**Screenshots**
![image](https://user-images.githubusercontent.com/4045116/54511604-ad74e600-490e-11e9-950d-cd4e2e95de34.png)

**Versions (please complete the following information):**
 - MacOS 10.14
 - Python 3.6.1 :: Anaconda custom (64-bit)
 - news-please Version latest

**Comment by fhamborg** [comment]
Could you please post the log for the same URL but using the http protocol, i,.e., `https://www.nytimes.com/2017/02/23/us/politics/cpac-stephen-bannon-reince-priebus.html?hp `

**Comment by mabodx** [comment]
What is the difference using http and https in your code?

**Comment by mabodx** [comment]
```Traceback (most recent call last):
  File "crawler.py", line 3, in <module>
    article = NewsPlease.from_url('http://www.nytimes.com/2017/02/23/us/politics/cpac-stephen-bannon-reince-priebus.html?hp')
  File "/Users/mabodx/anaconda/lib/python3.6/site-packages/newsplease/__init__.py", line 80, in from_url
    articles = NewsPlease.from_urls([url], timeout=timeout)
  File "/Users/mabodx/anaconda/lib/python3.6/site-packages/newsplease/__init__.py", line 103, in from_urls
    html = SimpleCrawler.fetch_url(url, timeout=timeout)
  File "/Users/mabodx/anaconda/lib/python3.6/site-packages/newsplease/crawler/simple_crawler.py", line 18, in fetch_url
    return SimpleCrawler._fetch_url(url, False, timeout=timeout)
  File "/Users/mabodx/anaconda/lib/python3.6/site-packages/newsplease/crawler/simple_crawler.py", line 31, in _fetch_url
    html = urllib.request.urlopen(req, data=None, timeout=timeout).read()
  File "/Users/mabodx/anaconda/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/mabodx/anaconda/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/Users/mabodx/anaconda/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/Users/mabodx/anaconda/lib/python3.6/urllib/request.py", line 564, in error
    result = self._call_chain(*args)
  File "/Users/mabodx/anaconda/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/Users/mabodx/anaconda/lib/python3.6/urllib/request.py", line 756, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/Users/mabodx/anaconda/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/Users/mabodx/anaconda/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/Users/mabodx/anaconda/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/Users/mabodx/anaconda/lib/python3.6/urllib/request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/Users/mabodx/anaconda/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error EOF occurred in violation of protocol (_ssl.c:749)>```

**Comment by fhamborg** [comment]
Strange.. I cannot reproduce the issue, it works fine on both computers I just tested, e.g.:
```
felix@fxa-2:~$ python3
Python 3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 03:13:28)
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from newsplease import NewsPlease
>>> article = NewsPlease.from_url('https://www.nytimes.com/2017/02/23/us/politics/cpac-stephen-bannon-reince-priebus.html?hp')
>>> print(article.title)
Stephen Bannon Reassures Conservatives Uneasy About Trump
>>>
```
However, this might be the same issue as mentioned at https://stackoverflow.com/questions/47478994/getting-urllib2-urlerror-urlopen-error-eof-occurred-in-violation-of-protocol. You could give it a try using the mentioned HTTPAdapter fix. Other than that, the issue seems to be at Python's urllib, but not of news-please.
